# Generated by Django 2.1.4 on 2019-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.CharField(max_length=550)),
            ],
        ),
    ]
