# Generated by Django 2.1.4 on 2019-04-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_material', models.CharField(choices=[('OURO', 'Ouro'), ('PRTA', 'Prata'), ('AÇOS', 'Aços')], default='', max_length=5)),
                ('type_item', models.CharField(choices=[('ANÉIS', 'Anéis'), ('COLARES', 'Colares'), ('BRINCOS', 'Brincos'), ('RELÓGIOS', 'Relógios'), ('PULSEIRAS', 'Pulseiras'), ('OUTROS', 'Outros')], default='', max_length=10)),
                ('type_fornecedor', models.CharField(choices=[('Fornecedor1', 'Fornecedor1'), ('Fornecedor2', 'Fornecedor2'), ('Fornecedor3', 'Fornecedor3'), ('Fornecedor4', 'Fornecedor4'), ('Fornecedor5', 'Fornecedor5'), ('Fornecedor6', 'Fornecedor6'), ('Fornecedor7', 'Fornecedor7')], default='', max_length=30)),
                ('type_price', models.CharField(choices=[('0.50 - 5.00', '0.50 - 5.00'), ('6.00 - 20.00', '6.00 - 20.00'), ('21.00 - 50.00', '21.00 - 50.00'), ('51.00 - 100.00', '51.00 - 100.00'), ('101.00 - 200.00', '101.00 - 200.00'), ('201.00 - 300.00', '201.00 - 300.00'), ('301.00 - 400.00', '301.00 - 400.00'), ('401.00 - 500.00', '401.00 - 500.00'), ('501.00 - 600.00', '501.00 - 600.00'), ('601.00 - 700.00', '601.00 - 700.00'), ('701.00 - 800.00', '701.00 - 800.00'), ('801.00 - 900.00', '801.00 - 900.00'), ('901.00 - 1000.00', '901.00 - 1000.00'), ('1001.00 - 2000.00', '1001.00 - 2000.00'), ('2001.00 - 5000.00', '2001.00 - 5000.00')], default='', max_length=40)),
                ('reference', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image_1', models.ImageField(default='transferir', upload_to='static/catalog')),
                ('image_2', models.ImageField(default='transferir', upload_to='static/catalog')),
                ('image_3', models.ImageField(default='transferir', upload_to='static/catalog')),
                ('image_4', models.ImageField(default='transferir', upload_to='static/catalog')),
                ('is_hidden', models.BooleanField(default=False)),
                ('catalog', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Catalog')),
            ],
        ),
    ]
