# Generated by Django 2.1.4 on 2019-04-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=models.ImageField(default='transferir', upload_to='static/'),
        ),
    ]
