# Generated by Django 2.1.4 on 2019-04-26 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
