# Generated by Django 2.1.4 on 2019-04-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190426_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tamanho',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
